# Generated by Django 3.0.8 on 2020-07-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200714_1734'),
    ]

    operations = [

        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.CharField(max_length=500),
        ),

    ]
