# Generated by Django 3.0.8 on 2020-07-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200714_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='full_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.FloatField()),
                ('count', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.University')),
            ],
        ),
    ]
